# Generated by Django 3.1.2 on 2020-11-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('idClassroom', models.AutoField(primary_key=True, serialize=False)),
                ('Numberplace', models.CharField(max_length=45)),
                ('Room', models.IntegerField()),
                ('status', models.BinaryField()),
                ('Classroomcol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'classroom',
                'ordering': ['Room'],
            },
        ),
        migrations.CreateModel(
            name='Classroom_has_Softwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classroom_idClassroom', models.IntegerField()),
                ('Softwares_idSoftware', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom_softwares',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idCours', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Code', models.CharField(max_length=10)),
                ('Unit', models.CharField(max_length=6)),
                ('NumberHours', models.IntegerField()),
                ('Description', models.TextField()),
                ('status', models.BinaryField()),
            ],
            options={
                'db_table': 'cours',
                'ordering': ['NumberHours'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('idgroup', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('numberstudent', models.CharField(max_length=45)),
                ('Starting', models.DateField()),
                ('Ending', models.DateField()),
                ('numberduration', models.IntegerField()),
                ('numbertime', models.CharField(max_length=25)),
                ('status', models.BinaryField()),
                ('Created', models.DateTimeField()),
                ('Modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['Starting'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('idPrograms', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Code', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=255)),
                ('Requierements', models.CharField(max_length=45)),
                ('status', models.BinaryField()),
                ('Cours_idCours', models.IntegerField()),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('idSoftware', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=45)),
                ('Type', models.CharField(max_length=45)),
                ('Version', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'softwares',
                'ordering': ['Name'],
            },
        ),
    ]
