# Generated by Django 3.1.2 on 2020-11-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom_has_Softwares',
            new_name='Classroom_has_Software',
        ),
        migrations.RenameModel(
            old_name='Cours',
            new_name='Cour',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
        migrations.RenameModel(
            old_name='Softwares',
            new_name='Software',
        ),
        migrations.AlterModelTable(
            name='cour',
            table='cour',
        ),
    ]
