# Generated by Django 3.1.2 on 2020-11-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnels',
            new_name='Personnel',
        ),
        migrations.RenameModel(
            old_name='TeacherPreferences',
            new_name='TeacherPreference',
        ),
    ]
